{{- if .Values.crdInstall.enable }}
{{- if .Values.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  annotations:
    # create hook dependencies in the right order
    {{- include "crdInstallAnnotations" . | nindent 4 }}
    "helm.sh/hook-weight": "-7"
  labels:
    app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "crdInstallSelector" . | quote }}
  name: {{ include "crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
      {{- include "labels.selector" . | nindent 6 }}
  egress:
    - toEntities:
        - kube-apiserver
{{- end }}
{{- end }}
