{{- if .Values.crdInstall.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    # create hook dependencies in the right order
    {{- include "crdInstallAnnotations" . | nindent 4 }}
    "helm.sh/hook-weight": "-1"
  labels:
    app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "crdInstallSelector" . | quote }}
  name: {{ include "crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
        {{- include "labels.selector" . | nindent 8 }}
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset
          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.
          kubectl apply -f /data/ 2>&1
        image: "{{ .Values.crdInstall.kubectl.registry }}/{{ .Values.crdInstall.kubectl.image }}:{{ .Values.crdInstall.kubectl.tag }}"
        name: kubectl
        resources: {{- toYaml .Values.crdInstall.resources | nindent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          {{- with .Values.containerSecurityContext }}
            {{- . | toYaml | nindent 10 }}
          {{- end }}
        volumeMounts:
{{- range $path, $_ := .Files.Glob "files/**" }}
        - mountPath: /data/{{ $path | base }}
          name: {{ $path | base | trimSuffix ".yaml" }}
          subPath: {{ $path | base }}
{{- end }}
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsUser: 1000
        {{- with .Values.podSecurityContext }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      serviceAccountName: {{ include "crdInstall" . }}
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      ttlSecondsAfterFinished: 86400 # 24h
      volumes:
{{ $currentScope := . }}
{{- range $path, $_ := .Files.Glob "files/**" }}
    {{- with $currentScope }}
      - configMap:
          items:
          - key: content
            path: {{ $path | base }}
          name: {{ include "crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" }}
        name: {{ $path | base | trimSuffix ".yaml" }}
{{- end }}
{{- end }}
  ttlSecondsAfterFinished: 86400 # 24h
{{- end }}
