{{- if .Values.crdInstall.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "crdInstall" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-1"
    {{- include "crdInstallAnnotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "crdInstallSelector" . | quote }}
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
        {{- include "labels.selector" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "crdInstall" . }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 2000
        {{- with .Values.podSecurityContext }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      containers:
      - name: kubectl
        image: "{{ .Values.crdInstall.kubectl.registry }}/{{ .Values.crdInstall.kubectl.image }}:{{ .Values.crdInstall.kubectl.tag }}"
        command:
        - sh
        - -c
        - |
          set -o errexit ; set -o xtrace ; set -o nounset
          # piping stderr to stdout means kubectl's errors are surfaced
          # in the pod's logs.
          kubectl apply -f /data/ 2>&1
        securityContext:
          readOnlyRootFilesystem: true
          {{- with .Values.containerSecurityContext }}
            {{- . | toYaml | nindent 10 }}
          {{- end }}
        volumeMounts:
{{- range $path, $_ := .Files.Glob "files/**" }}
        - name: {{ $path | base | trimSuffix ".yaml" }}
          mountPath: /data/{{ $path | base }}
          subPath: {{ $path | base }}
{{- end }}
        resources: {{- toYaml .Values.crdInstall.resources | nindent 10 }}
      volumes:
{{ $currentScope := . }}
{{- range $path, $_ := .Files.Glob "files/**" }}
    {{- with $currentScope }}
      - name: {{ $path | base | trimSuffix ".yaml" }}
        configMap:
          name: {{ include "crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" }}
          items:
          - key: content
            path: {{ $path | base }}
{{- end }}
{{- end }}
      restartPolicy: Never
  backoffLimit: 4
{{- end }}
