{{/*
We have to create individual configmaps for each CRD - they exceed the total
allowed length for a configmap if they are combined.
*/}}
{{ $currentScope := . }}
{{- if .Values.crdInstall.enable }}
  {{- range $path, $_ := .Files.Glob "files/**" }}
    {{- with $currentScope }}
---
apiVersion: v1
data:
  content: |
{{ tpl ($.Files.Get $path) . | indent 4 }}
kind: ConfigMap
metadata:
  annotations:
    # create hook dependencies in the right order
    {{- include "crdInstallAnnotations" . | nindent 4 }}
    "helm.sh/hook-weight": "-5"
  labels:
    app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "crdInstallSelector" . | quote }}
  name: {{ include "crdInstall" . }}-{{ $path | base | trimSuffix ".yaml" }}
  namespace: {{ .Release.Namespace | quote }}
    {{- end }}
  {{- end }}
{{- end }}
