{{- if .Values.crdInstall.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # create hook dependencies in the right order
    {{- include "crdInstallAnnotations" . | nindent 4 }}
    "helm.sh/hook-weight": "-4"
  labels:
    app.kubernetes.io/component: {{ include "crdInstall" . | quote }}
    {{- include "labels.selector" . | nindent 4 }}
    role: {{ include "crdInstallSelector" . | quote }}
  name: {{ include "crdInstall" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
