---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: common-labels
labels:
  app.kubernetes.io/managed-by: "{{ .Release.Service }}"
  app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
  helm.sh/chart: "{{ .Chart.Name }}"
  app.kubernetes.io/name: "{{ .Chart.Name }}"
  app.kubernetes.io/instance: "{{ .Release.Name }}"
fieldSpecs:
  - path: metadata/labels
    create: true
