name: check generated yamls

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  check:
    name: check generated yamls
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: generate manifests
      run: make all
    - name: check no change
      run: git diff --quiet --exit-code && [ -z "$(git status --porcelain)" ]
