name: check generated yamls

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  check:
    name: check generated yamls
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'skip-ci') }}
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
    - name: generate manifests
      run: make all
    - name: check no change
      run: git diff --quiet --exit-code && [ -z "$(git status --porcelain)" ]
